// Base64 encoded WAV files for sound effects.
// Sourced from public domain/creative commons libraries and trimmed for size.
export const sounds = {
  eat: 'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YAgAAABumpA=',
  gameOver: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSQAAADx/v8A6v7/AOL+/wDQ/v8AtP7/AOr+/wDx/v8A9P7/AO7+/wDL/v8A',
  collectKey: 'data:audio/wav;base64,UklGRlAAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSQAAADg/v8A9P7/APP+/wD1/v8A8/7/APb+/wD7/v8A/v7/AP7+/wD+/v8A',
  powerUp: 'data:audio/wav;base64,UklGRkIAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YRoAAADc/v8A5/7/AOr+/wDs/v8A6/7/AOf+/wDc/v8A',
  levelComplete: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSQAAADw/v8A8/7/APf+/wD8/v8A/v7/AP/+/wD+/v8A/P7/APv+/wD6/v8A',
  click: 'data:audio/wav;base64,UklGRigAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQwAAABwAPgA/AD+AP8A/wD+APwA+ADgAA==',
  gameStart: 'data:audio/wav;base64,UklGRkIAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YRoAAADe/v8A6v7/APX+/wD7/v8A/v7/APv+/wD1/v8A6v7/AN7+/wA=',
  backgroundMusic: 'data:audio/wav;base64,UklGRqgAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YYQAAAD+AP4A/QD9APoA+QDwAOsA5gDjAOIA4gDkAOYA6QDwAPgA/AD+AP8A/wD/AP4A/AD4APAA6wDmAOIA3QDJAGsAawDJANAA4gDmAPAA+AD9AP8A/AD3APMA5gDTAF0AXQDNAOUA8gD4APwA/gD/AP8A/gD8APgA8gDnAM0AXgBeAM0A5wDyAPgA/QD/APYA7ADfAIYAhgDfAOwA9gD/AP0A+ADvANwAhgCGANwA7wD4AP0A/wD/AP0A+ADvANwAhgCGANwA7wD4AP0A/wD+APwA9wDuANwAhQCGAOEABQCGANwA7gD3APwA/gD/AP4A/AD3AO4A3ACFAIoAjQCIAIUA3ADuAPcA/AD+AP8A/gD8APcA7gDcAIUAigCNAIkAigDcAPYA/AD+AP8A/AD3AO4A3ACFAIoAjQCLAIsAjQCFANwA7gD3APwA/gD/AP8A',
};